# Generated by Django 5.0.6 on 2026-04-17 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('specialization', models.CharField(choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('surgery', 'Surgery'), ('urology', 'Urology'), ('other', 'Other')], default='general_practice', max_length=50, verbose_name='Specialization')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='License Number')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qualification')),
                ('hospital', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hospital/Clinic')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consultation Fee (INR)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Consultation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
                'ordering': ['-created_at'],
            },
        ),
    ]
